App/urls.py
'''
  @author Karan Dave  
'''

from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='HomePage'),
    path('about/', views.about, name='About'),
    path('msg/', views.msg, name='msg'),
    path('blog/', views.blog, name='blog'),
    path('detail/', views.detail, name='detail'),
    path('send/', views.send, name='send'),
    path('requests/', views.requests, name='requests'),
    path('Accept/', views.Accept, name='Accept'),
    path('work/', views.work, name='work'),
    path('Followers/', views.Followers, name='Followers'),
    path('Following/', views.Following, name='Following'),
    path('remove/', views.remove, name='remove'),
    path('unfollow/', views.unfollow, name='unfollow'),
    path('cart/', views.cart, name='cart'),
    path('cartItem/', views.cartItem, name='cartItem'),
    path('Cremove/', views.Cremove, name='Cremove'),
    path('Save/', views.Save, name='Save'),
    path('usave/', views.usave, name='usave'),
    path('delete/', views.delete, name='delete'),
    path('LKS/', views.LKS, name='LKS'),
    path('Category/', views.Category, name='Category'),
    path('posts/', views.posts, name='posts'),
    path('feedback/', views.feedback, name='feedback'),
    path('chat/', views.chat, name='chat'),
    path('cleartalk/', views.cleartalk, name='cleartalk'),
    path('makepb/', views.makepb, name='makepb'),
    path('makepv/', views.makepv, name='makepv'),
    path('psdt/', views.psdt, name='psdt'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.payment, name='payment'),
    path('mypurchased/', views.mypurchased, name='mypurchased'),
    path('order_history/', views.order_history, name='order_history'), 
    path('sorder/', views.sorder, name='sorder'),
    path('Testimonials/', views.Testimonials, name='Testimonials'),
    
]

DSPOT/urls.py
"""
Created by : Karan Dave
"""

from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/',admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('outh/', include('allauth.urls')),
    path('',views.home,name='index'),
    path('home/',include('App.urls')),
    path('Account/', include('Account.urls')),
    path('payment/', include('Payment.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Payment/urls.py
from django.urls import path
from .views import initiate_payment, callback
from . import views

urlpatterns = [
    path('pay/<int:Did>', views.initiate_payment, name='pay'),
    path('callback/', views.callback, name='callback'),
]

Account/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.conf import settings
User = settings.AUTH_USER_MODEL


class LoggedInUser(models.Model):
    user = models.CharField(max_length=32, null=False, blank=False)
    # Session keys are 32 characters long
    session_key = models.CharField(max_length=32, null=False, blank=False)

    def __str__(self):
        return self.user


class Messages(models.Model):
    UserName = models.CharField(max_length=50)
    Subject = models.CharField(max_length=50)
    Query = models.TextField(max_length=300)

    def __str__(self):
        return self.UserName


class Reply(models.Model):
    UserName = models.CharField(max_length=50)
    Subject = models.CharField(max_length=50, null=False, default=" ")
    Query = models.TextField(max_length=300, default=" ")
    Response = models.TextField(max_length=300)
    

    def __str__(self):
        return self.UserName


class Draft_Box(models.Model):
    UserName = models.CharField(max_length=50)
    Subject = models.CharField(max_length=50)
    Query = models.TextField(max_length=300)
    Status=models.BooleanField(default=False)
    Response = models.TextField(max_length=300,default=" ")

    def __str__(self):
        return self.UserName


class Profile(models.Model):

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=False, default='')
    Profile_Image = models.ImageField(
        upload_to='Profile_Image', default='user.jpg')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        img = Image.open(self.Profile_Image.path)

        if img.width > 300 or img.height > 300:
            re_size = (300, 300)
            img.thumbnail(re_size)
            img.save(self.Profile_Image.path)

Payment/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Transaction(models.Model):
    made_by = models.ForeignKey(User, related_name='transactions',
                                on_delete=models.CASCADE)
    made_on = models.DateTimeField(auto_now_add=True)
    amount = models.IntegerField()
    order_id = models.CharField(
        unique=True, max_length=100, null=True, blank=True)
    checksum = models.CharField(max_length=200, null=True, blank=True)
    Design_No = models.IntegerField(default=0)
    Creator=models.CharField(max_length=200, null=True, blank=True)
    Status=models.CharField(max_length=100, null=True, blank=True)


    def __str__(self):
        return str(self.made_by)

    def save(self, *args, **kwargs):
        if self.order_id is None and self.made_on and self.id:
            self.order_id = self.made_on.strftime(
                'PAY2ME%Y%m%dODR') + str(self.id)
        return super().save(*args, **kwargs)

Payment/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from .models import Transaction
from .Paytm import generate_checksum, verify_checksum
from django.contrib.auth.decorators import login_required
from App.models import FollowRequest, Work, Carts, Saved, Likes, Feedbk, Chat
from django.contrib.auth.models import User, auth


@login_required
def initiate_payment(request, Did):
    if request.method == "GET":
        return render(request, 'pay.html')
    try:
        username = request.POST['username']
        password = request.POST['password']
        temp= User.objects.filter(first_name=username)
        
        for i in temp:
            username=i
        user = authenticate(request, username=username, password=password)

        if user is None:
            raise ValueError
        auth_login(request=request, user=user)
    except:
        return render(request, 'pay.html')

    Data = Carts.objects.filter(UserName=request.user, Design_No=Did)

    pp = Work.objects.filter(id=Did)
    for i in pp:
        Price=(i.Price)
        name=(i.Your_Name)
    transaction = Transaction.objects.create(made_by=user, amount=Price,Design_No=Did,Creator=name)
    transaction.save()
    Carts.objects.filter(UserName=request.user,Design_No=Did).delete()
    merchant_key = settings.PAYTM_SECRET_KEY

    params = (
        ('MID', settings.PAYTM_MERCHANT_ID),
        ('ORDER_ID', str(transaction.order_id)),
        ('CUST_ID', str(transaction.made_by.email)),
        ('TXN_AMOUNT', str(transaction.amount)),
        ('CHANNEL_ID', settings.PAYTM_CHANNEL_ID),
        ('WEBSITE', settings.PAYTM_WEBSITE),
        # ('EMAIL', request.user.email),
        # ('MOBILE_N0', '9911223388'),
        ('INDUSTRY_TYPE_ID', settings.PAYTM_INDUSTRY_TYPE_ID),
        ('CALLBACK_URL', 'http://127.0.0.1:8000/payment/callback/'),
        # ('PAYMENT_MODE_ONLY', 'NO'),
    )

    paytm_params = dict(params)
    checksum = generate_checksum(paytm_params, merchant_key)
    
    transaction.checksum = checksum
    transaction.save()

    paytm_params['CHECKSUMHASH'] = checksum
    print('SENT: ', checksum)
    return render(request, 'redirect.html', context=paytm_params)


@csrf_exempt
def callback(request):
    if request.method == 'POST':
        paytm_checksum = ''
        print(request.body)
        print(request.POST)
        received_data = dict(request.POST)
        print(received_data)
        paytm_params = {}
        paytm_checksum = received_data['CHECKSUMHASH'][0]
        for key, value in received_data.items():
            if key == 'CHECKSUMHASH':
                paytm_checksum = value[0]
            else:
                paytm_params[key] = str(value[0])
        # Verify checksum
        is_valid_checksum = verify_checksum(paytm_params, settings.PAYTM_SECRET_KEY, str(paytm_checksum))
        if is_valid_checksum:
            print("Checksum Matched")
            received_data['message'] = "Checksum Matched"
            Transaction.objects.filter(order_id=paytm_params['ORDERID']).update(Status=str(paytm_params['STATUS']))
         
        else:
            print("Checksum Mismatched")
            received_data['message'] = "Checksum Mismatched"
            Transaction.objects.filter(order_id=paytm_params['ORDERID']).update(Status=str(paytm_params['STATUS']))

        return render(request, 'callback.html', context=received_data)

App/templates/AboutUser.html
{%extends 'basic.html'%}
{% load static%}

{% block title%}
{% for i in obj %}About {{i.username}}{% endfor %}
{%endblock%}

{% block body%}
<style>
    /* The popup chat - hidden by default */
    .chat-popup {
        display: block;
        position: fixed;
        bottom: 0;
        right: 15px;
        border: 3px solid #f1f1f1;
        z-index: 9;
    }

    /* Add styles to the form container */
    .form-container {
        max-width: 300px;
        padding: 10px;
        background-color: white;
    }

    /* Full-width textarea */
    .form-container input {
        width: 100%;
        cursor: pointer;
        border-radius: 20px;
        padding: 15px;
        background-color: #252525;
        color: aliceblue;
        margin-top: 20px;
    }

    /* Set a style for the submit/send button */
    .form-container .btn {
        padding: 16px 20px;
        border: none;
        cursor: pointer;
        width: 100%;
        margin-bottom: 10px;
        opacity: 0.8;
        margin-top: 10px;
    }


    /* Add some hover effects to buttons */
    .form-container .btn:hover,
    .open-button:hover {
        opacity: 1;
    }
    
</style>

<center>
    {% for i in obj %}
    <section class="text-gray-700 body-font" style="margin-top: 5%;">
        <div class="container px-5 py-0 mx-auto">
            <div class="flex flex-col text-center w-full mb-20">
                {% if i.last_name == 'Professional' %}
                <h1 class="text-gray-900 title-font font-medium mb-1 mt-4"><span style="background-color: goldenrod; padding: 10px;border-radius: 20px;"><i class="fa fa-user-shield"></i> Professional
                    Account</span></h1>
                {%else%}
                <h1 class="text-gray-900 title-font font-medium mb-1 mt-4"><span style="background-color: goldenrod; padding: 10px;border-radius: 20px;"><i class="fa fa-user-lock"></i> General
                        Account</span></h1>
                {% endif %}
            </div>
        </div>
    </section>
    {% endfor %}
    <section>
        <div class="container">
            <div>
                <div class="lg:w-1/2 w-full">
                    <div class="flex mb-4">
                        {% for i in obj %}
                        {% if i.last_name == 'Professional' %}
                        <a class="flex-grow text-indigo-500 py-2 text-lg px-1" title=" Posts"><button
                                class="genric-btn primary-border circle "><i class="fa fa-folder-plus"></i>:
                                {{post}}</button></a>
                        {% endif %}
                        {% endfor %}
                        <a class="flex-grow text-indigo-500 py-2 text-lg px-1" title="Followers"><button
                                class="genric-btn primary-border circle ml-2"><i class="fa fa-user-plus"></i>
                                : {{obj3}}</button></a>
                        <a class="flex-grow text-indigo-500 py-2 text-lg px-1" title="Following"><button
                                class="genric-btn primary-border circle ml-2"><i class="fa fa-user-check"></i>
                                : {{obj2}}</button></a>
                    </div>
                    {% for i in obj %}
                    <center>
                        <input type="text" class="form-control w-50" value="{{i.username}}" readonly>
                        <input type="email" class="form-control w-50 mt-4" value="{{i.email}}" readonly>
                    </center>
                        <!-- <div class="flex py-2">
                            <input type="text" class="form-control w-50" value="{{i.username}}" readonly>
                        </div>
                        <div class="flex py-2">
                            <input type="email" class="form-control w-50" value="{{i.email}}" readonly>
                        </div> -->
            
                    <!-- <div class="flex py-2">
                        <input type="tel" class="form-control" value="{{i.first_name}}" readonly>
                    </div> -->

                    {% if i.username != user.username%}
                    <form action="/home/send/" method='post' enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for j in obj1 %}

                        <center>
                            {% if j.UserName == i.username and j.Sender == user.username and j.Status == True %}
                            <input type="button" value="Following" class="genric-btn danger radius mt-2 w-full">
                            {% elif j.UserName == i.username and j.Sender == user.username and j.Status == False  %}
                            <input type="button" value="Requested" class="genric-btn danger radius mt-2 w-full">
                            {% endif %}
                        </center>

                        {% empty %}

                        <center>
                            <input type="hidden" name='FW' value="{{i.username}}">
                            <input title="Send Follow Request" type="submit" value="+ Follow"
                                class="genric-btn info radius mt-2  w-full">
                        </center>

                        {% endfor %}
                    </form>


                    <center><button type="button" class="genric-btn primary radius mt-2 mb-4 w-full" data-toggle="modal"
                            data-target="#MessageModal"><i class="fas fa-paper-plane"></i> Talk With
                            {{i.username}}</button></center>

                    <!-- Message Modal -->
                    <div class="modal fade" id="MessageModal" tabindex="-1" role="dialog" aria-labelledby="MessageModal"
                        aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content" style="margin-top: 16%;">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form method="post" action="/home/chat/" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div>
                                            <h2>Chat With {{i.username}}</h2>
                                            <input type="hidden" name='chatuser' value="{{i.username}}">
                                            {% for t in msg1 %}
                                            <label style="float: right;margin-top: 10px;">{{t.Message}}
                                                {{t.DateTime}}</label><br><br>
                                            {% endfor %}

                                            {% for t in msg2 %}
                                            <label style="float: left;margin-top: 10px;">{{t.Message}}
                                                {{t.DateTime}}</label><br><br>
                                            {% endfor %}

                                        </div><br>
                                        <div>
                                            <input style="width:100%;cursor: pointer;border-radius: 20px;" id="message"
                                                type="text" name="msg" placeholder="Type Message Here..... "
                                                class="form-control" required>
                                        </div><br>
                                        <button type="submit" class="genric-btn info radius mt-2  w-full">Send</button>
                                    </form>
                                    <form method="post" action="/home/cleartalk/" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <input type="hidden" name='chatuser' value="{{i.username}}">
                                        <button type="submit" class="genric-btn danger radius mt-2  w-full">Clear
                                            Conversation
                                        </button>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>

                    {% endif %}
                    {% endfor %}

                </div>
            </div>
    </section>
</center>


{%endblock%}

App/templates/Cart.html
{%extends 'basic.html'%}
{% load static%}
{% block title%}{{user.username}}'s Cart{%endblock%}


{% block body%}
<style>
    .banner {
      position: relative;
      width: 300px;
      /* height: 150px; */
      overflow: hidden;
      margin-left: auto;
      margin-right: auto;

    }

  </style>

<section class="text-gray-700 body-font"  style="padding-top: 5rem;">
    <div class="container px-5 mx-auto">
        <!-- <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Your Cart</h1>
        </div> -->
        <!-- <div class="flex flex-wrap -m-4">
            {%for i in obj%}

            <div class="p-4 md:w-1/3">
                <div class="h-full border-2 border-gray-200 rounded-lg overflow-hidden">
                    {%for j in obj1%}
                    {% if j.Creater == i.Creater and j.id == i.Design_No%}
                    <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="{{j.Content.url}}" alt="blog">
                    {% endif %}
                    {% endfor %}
                    <div class="p-6">
                        <form action="/home/detail/" method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                            <center>
                                <input type="hidden" name='FW' value="{{i.Creater}}">
                                <button class="genric-btn info radius mt-2  w-full" style="margin-top: 10px;"><i
                                        class="fa fa-user-circle"></i> About {{i.Creater}}</button>
                            </center>
                        </form>

                        <form action="/home/Cremove/" method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                            <center>
                                <input type="hidden" name='FW' value="{{i.Design_No}}">
                                <button class="genric-btn danger radius mt-2  w-full"style="margin-top: 10px;"><i
                                        class="fa fa-trash"></i> Remove From Cart</button>
                            </center>
                        </form>

                        <form action="/home/checkout/" method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                            <center>
                                <input type="hidden" name='FW' value="{{i.Design_No}}">
                                <button class="genric-btn primary radius mt-2  w-full" style="margin-top: 10px;"><i
                                        class="fa fa-shopping-bag"></i> Check Out</button>
                            </center>
                        </form>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="flex flex-col text-center w-full mb-20">
                <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900" style="color:red">Your Cart
                    Is Empty</h1>
            </div>
            {% endfor %}
        </div> -->

        <div class="row">
            {%for i in obj%}
            {%for j in obj1%}
            {% if j.Your_Name == i.Creater and j.id == i.Design_No%}
            <div class="col-md-4 mb-10">
                <div class="card mb-4 shadow-sm" style="border-radius: 20px;">
                    <div class="card-body">
                        <center><img src="{{j.Upload_Pictures.url}}" class="rounded-lg h-64 overflow-hidden"></center>
                        <form action="/home/detail/" method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                            <center>
                                <input type="hidden" name='FW' value="{{j.Your_Name}}">
                                <button type="submit" class="genric-btn primary-border circle mt-3"><i
                                        class="fa fa-user-circle"></i> About {{j.Your_Name}}</button>
                            </center>
                        </form>

                        <form action="/home/checkout/" method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                            <center>
                                <input type="hidden" name='FW' value="{{i.Design_No}}">
                                <button type="submit" class="genric-btn primary-border circle mt-3"><i
                                        class="fa fa-shopping-bag"></i> Check Out</button>
                            </center>
                        </form>

                        <form action="/home/Cremove/" method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                            <center>
                                <input type="hidden" name='FW' value="{{i.Design_No}}">
                                <button type="submit" class="genric-btn primary-border circle mt-3"><i
                                        class="fa fa-trash"></i> Remove From Cart</button>
                            </center>
                        </form>

                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor%}
            {% empty %}
            <div class="flex flex-col text-center w-full mb-20 mt-20">
                <img src="/static/CART.svg" class="banner"><br>
                <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900" style="color:red">Your Cart Is Empty</h1>
            </div>
            {% endfor %}
        </div>
    </div>
</section>



{%endblock%}

App/templates/Followers.html
{%extends 'basic.html'%}
{% load static%}
{% block title%}{{user.username}}'s Followers{%endblock%}


{% block body%}
<style>
    .banner {
      position: relative;
      width: 300px;
      /* height:auto; */
      overflow: hidden;
      margin-left: auto;
      margin-right: auto;

    }

  </style>

<section class="text-gray-700 body-font overflow-hidden"  style="padding-top: 5rem;">
    <div class="container">
        <!-- <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-black-900">Your Followers</h1>
        </div> -->
        <div class="flex flex-wrap -m-4">
            {% for i in obj %}
            <div class="p-4 xl:w-1/4 md:w-1/2 w-full">
                <div class="h-full p-6 rounded-lg border-2 border-indigo-500 flex flex-col relative overflow-hidden">
                    {% for j in obj1 %}
                    {% if j.username == i.Sender %}
                    <center><img alt="testimonial"
                            class="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100"
                            src="{{j.profile.Profile_Image.url}}"></center>
                    {% endif %}
                    {% endfor%}
                    <h1
                        class="text-5xl text-gray-900 leading-none flex items-center pb-4 mb-4 border-b border-gray-200">
                        {{i.Sender}}
                    </h1>

                    <form action="/home/detail/" method='post' enctype="multipart/form-data">
                        {% csrf_token %}
                        <center>
                            <input type="hidden" name='FW' value="{{i.Sender}}">
                            <input title="Get Details" type="submit" value="About {{i.Sender}}" class="genric-btn info radius"
                                style="font-weight: bolder;cursor: pointer;width: 100%;" id="btns">
                        </center>
                    </form>
                    <form action="/home/remove/" method='post' enctype="multipart/form-data">
                        {% csrf_token %}
                        <center>
                            <input type="hidden" name='FW' value="{{i.Sender}}">
                            <input type="submit" value="Remove {{i.Sender}} " class="genric-btn danger radius"
                                style="font-weight: bolder;cursor: pointer;width: 100%;margin-top: 10px;" id="btns">
                        </center>
                    </form>
                </div>
            </div>
            {% empty %}
            <div class="flex flex-col text-center w-full mb-20 mt-12">
                <img src="/static/FOLLOWER.svg" class="banner"><br>
                <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900" style="color:red">You Have No Any Follower</h1>
            </div>
            {% endfor%}

        </div>
    </div>
</section>
{%endblock%}

App/templates/Following.html
{%extends 'basic.html'%}
{% load static%}
{% block title%}{{user.username}}'s Following{%endblock%}


{% block body%}
<style>
    .banner {
      position: relative;
      width: 300px;
      /* height:auto; */
      overflow: hidden;
      margin-left: auto;
      margin-right: auto;

    }

  </style>

<section class="text-gray-700 body-font overflow-hidden"  style="padding-top: 5rem;">
    <div class="container">
        <!-- <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-black-900">Your Following
            </h1>
        </div> -->
        <div class="flex flex-wrap -m-4">
            {% for i in obj %}
            <div class="p-4 xl:w-1/4 md:w-1/2 w-full">
                {% for j in obj1 %}
                {% if j.username == i.UserName %}
                <div class="h-full p-6 rounded-lg border-2 border-indigo-500 flex flex-col relative overflow-hidden">
                    <center><img alt="testimonial"
                            class="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100"
                            src="{{j.profile.Profile_Image.url}}"></center>
                    {% endif %}
                    {% endfor%}
                    <h1
                        class="text-5xl text-gray-900 leading-none flex items-center pb-4 mb-4 border-b border-gray-200">
                        {{i.UserName}}
                    </h1>

                    <form action="/home/detail/" method='post' enctype="multipart/form-data">
                        {% csrf_token %}
                        <center>
                            <input type="hidden" name='FW' value="{{i.UserName}}">
                            <input title="Get Details" type="submit" value="About {{i.UserName}}" class="genric-btn info radius"
                                style="font-weight: bolder;cursor: pointer;width: 100%;" id="btns">
                        </center>
                    </form>
                    <form action="/home/unfollow/" method='post' enctype="multipart/form-data">
                        {% csrf_token %}
                        <center>
                            <input type="hidden" name='FW' value="{{i.UserName}}">
                            <input type="submit" value="Unfollow {{i.UserName}} " class="genric-btn danger radius"
                                style="font-weight: bolder;cursor: pointer;width: 100%;margin-top: 10px;" id="btns">
                        </center>
                    </form>

                </div>
            </div>

            {% empty %}
            <div class="flex flex-col text-center w-full mb-20 mt-12">
                <img src="/static/FOLLOWER.svg" class="banner"><br>
                <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900" style="color:red">You Have No
                    Following</h1>
            </div>
            {% endfor%}

        </div>

    </div>
</section>



{%endblock%}

App/templates/updateprofile.html
{%extends 'basic.html'%}
{% load static%}
{% load crispy_forms_tags %}
{% block title%}{{user.username}}'s Profile{%endblock%}


{% block body%}

<style>
    a {
       color: navy;
    }
    a:hover {
       color: black;
    }
    #id_Profile_Image
    {
        color: navy;
    }
    center{
        margin-top: 3%;
    }
    label{
        color: red; 
        visibility: hidden; 
    }
    div{
        color: red;
        margin-top: 10px;
    }
    input{
        padding-top: 20px;
        max-width: 50%;
    }
    h1{
        margin-top: 10px;
    }


</style>


<center  style="padding-top: 5rem;">
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <fieldset class="form-group"
            style="width:80%;font-weight: bolder;justify-content: center;border:  black double ;border-radius: 20px;">
            <!-- {{ u_form|crispy }} -->
            <h1 class="text-gray-900 title-font font-medium mb-1 mt-4"><span style="background-color: goldenrod; padding: 10px;border-radius: 20px;"><i class="fa fa-user-cog"></i> Profile Setting</span></h1>
            {{ p_form |crispy }}

        </fieldset>
        <button type="submit" class="genric-btn info radius">Save Changes</button>
        
    </form>
</center>

{%endblock%}